[package]
name = "nickel"
version = "0.1.0"
authors = ["nur"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nickel = "0.11.0"
tokio = { version = "1", features = ["full"] }